---

version: '3.2'

services:
  composer:
    build: composer
    command: bash -c 'cd /app && php /opt/php/bin/composer install'
    volumes:
      - type: bind
        source: ./app
        target: /app
  php-fpm:
    image: library/php:7.3-fpm
    volumes:
      - type: bind
        source: ./app
        target: /app
    ports:
      - "9000:9000"
    depends_on:
      - composer
  web:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./conf/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
